package Principal;

import Vistas.PanelEmpleados;
import Vistas.PanelFacturas;
import Vistas.PanelFamilias;
import Vistas.PanelProductos;
import Vistas.PanelVentas;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;

/**
 * Clase principal que se encarga de mostrar los datos e interactuar con
 * el usuario
 * 
 * @author yosua
 */
public class TPVFrame extends javax.swing.JFrame {

    /**
     * Creates new form TPVFrame
     */
    public TPVFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        loging();
    }

    /**
     * Método para permitir el acceso a la aplicación y permitir el cambio de
     * usuarios
     */
    private void loging() {
        panelContenedor.removeAll();
        PanelEmpleados log = new PanelEmpleados(this);
        panelContenedor.add(log.getPanelLoging(), java.awt.BorderLayout.CENTER);
        barraMenus.setVisible(false);
        pack();

    }

    /**
     * Método con el que controlamos que solo admin pueda realizar cambios
     *
     * @return true si esta autorizado, false en caso contrario
     */
    private boolean usuarioAutorizado() {
        final String AUTORIZADO = "admin";
        if (lblUsuarioActivo.getText().equals(AUTORIZADO)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioActivo = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        barraMenus = new javax.swing.JMenuBar();
        menuTPV = new javax.swing.JMenu();
        menuTPVVentas = new javax.swing.JMenuItem();
        menuTPVEditar = new javax.swing.JMenu();
        menuTPVEditarFamilias = new javax.swing.JMenuItem();
        menuTPVEditarProductos = new javax.swing.JMenuItem();
        menuTPVSeparador = new javax.swing.JPopupMenu.Separator();
        menuTPVFacturas = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        menuEmpleadoEditar = new javax.swing.JMenuItem();
        menuEmpleadoCerrar = new javax.swing.JMenuItem();

        lblUsuarioActivo.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));

        panelContenedor.setPreferredSize(new java.awt.Dimension(800, 800));
        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        menuTPV.setText("TPV");

        menuTPVVentas.setText("Ventas");
        menuTPVVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTPVVentasActionPerformed(evt);
            }
        });
        menuTPV.add(menuTPVVentas);

        menuTPVEditar.setText("Editar TPV");

        menuTPVEditarFamilias.setText("Editar Familias");
        menuTPVEditarFamilias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTPVEditarFamiliasActionPerformed(evt);
            }
        });
        menuTPVEditar.add(menuTPVEditarFamilias);

        menuTPVEditarProductos.setText("Editar Productos");
        menuTPVEditarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTPVEditarProductosActionPerformed(evt);
            }
        });
        menuTPVEditar.add(menuTPVEditarProductos);

        menuTPV.add(menuTPVEditar);
        menuTPV.add(menuTPVSeparador);

        menuTPVFacturas.setText("Facturas");
        menuTPVFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTPVFacturasActionPerformed(evt);
            }
        });
        menuTPV.add(menuTPVFacturas);

        barraMenus.add(menuTPV);

        menuEmpleados.setText("Empleados");

        menuEmpleadoEditar.setText("Editar empleados");
        menuEmpleadoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoEditarActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuEmpleadoEditar);

        menuEmpleadoCerrar.setText("Cerrar sesión");
        menuEmpleadoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoCerrarActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuEmpleadoCerrar);

        barraMenus.add(menuEmpleados);

        setJMenuBar(barraMenus);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpleadoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoCerrarActionPerformed
        loging();
        this.setTitle("");
    }//GEN-LAST:event_menuEmpleadoCerrarActionPerformed

    private void menuEmpleadoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoEditarActionPerformed
        if (usuarioAutorizado()) {
            panelContenedor.removeAll();
            PanelEmpleados editar = new PanelEmpleados(this);
            panelContenedor.add(editar, java.awt.BorderLayout.CENTER);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no autorizado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuEmpleadoEditarActionPerformed

    private void menuTPVEditarFamiliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTPVEditarFamiliasActionPerformed
        if (usuarioAutorizado()) {
            panelContenedor.removeAll();
            PanelFamilias editar = new PanelFamilias(this);
            panelContenedor.add(editar, java.awt.BorderLayout.CENTER);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no autorizado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuTPVEditarFamiliasActionPerformed

    private void menuTPVEditarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTPVEditarProductosActionPerformed
        if (usuarioAutorizado()) {
            panelContenedor.removeAll();
            PanelProductos editar = new PanelProductos(this);
            panelContenedor.add(editar, java.awt.BorderLayout.CENTER);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no autorizado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuTPVEditarProductosActionPerformed

    private void menuTPVVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTPVVentasActionPerformed
        panelContenedor.removeAll();
        barraMenus.setVisible(false);
        PanelVentas ventas = new PanelVentas(this);
        panelContenedor.add(ventas, java.awt.BorderLayout.CENTER);
        pack();
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_menuTPVVentasActionPerformed

    private void menuTPVFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTPVFacturasActionPerformed
        if (usuarioAutorizado()) {
            panelContenedor.removeAll();
            PanelFacturas factura = new PanelFacturas(this);
            panelContenedor.add(factura, java.awt.BorderLayout.CENTER);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no autorizado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuTPVFacturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JLabel lblUsuarioActivo;
    private javax.swing.JMenuItem menuEmpleadoCerrar;
    private javax.swing.JMenuItem menuEmpleadoEditar;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuTPV;
    private javax.swing.JMenu menuTPVEditar;
    private javax.swing.JMenuItem menuTPVEditarFamilias;
    private javax.swing.JMenuItem menuTPVEditarProductos;
    private javax.swing.JMenuItem menuTPVFacturas;
    private javax.swing.JPopupMenu.Separator menuTPVSeparador;
    private javax.swing.JMenuItem menuTPVVentas;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter de la barraMenus
     *
     * @return barraMenus
     */
    public JMenuBar getBarraMenus() {
        return barraMenus;
    }

    /**
     * Getter del lblUsuarioActivo
     *
     * @return JLabel lblUsuarioActivo
     */
    public JLabel getLblUsuarioActivo() {
        return lblUsuarioActivo;
    }

}
