package Vistas;

import Principal.TPVFrame;
import Ventas.entities.AccionesVentas;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;

/**
 *
 * @author yosua
 */
public class PanelVentas extends javax.swing.JPanel implements Runnable {

    private TPVFrame frame;
    private AccionesVentas acciones;
    private Thread h1;

    public PanelVentas(TPVFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesVentas(this);
        cargarComponentes();
    }

    /**
     * Método para cargar todos los componentes de inicio del panel
     */
    private void cargarComponentes() {
        acciones.cargarFamilia();
        acciones.cargarTablaCuenta();
        acciones.cargarVendedores();
        acciones.cargarClientes();
        acciones.cargarBarraMesas();
        acciones.cargarNumeroFactura();
        h1 = new Thread(this);
        h1.start();
    }

    /**
     * Sobrecarga del método run para mostrar la hora
     */
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            GregorianCalendar calendario = new GregorianCalendar();
            String dia = calendario.getTime().toString();
            lblHora.setText(dia);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diagCantidades = new javax.swing.JDialog();
        lblTituloCantidades = new javax.swing.JLabel();
        spnCantidades = new javax.swing.JSpinner();
        btnCantidadesAceptar = new javax.swing.JButton();
        btnGrpBarraMesas = new javax.swing.ButtonGroup();
        panelBtnFamilia = new javax.swing.JPanel();
        lblFamilias = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        panelBtnProductos = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        panelCuenta = new javax.swing.JPanel();
        scpTablaCuenta = new javax.swing.JScrollPane();
        tablaCuenta = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        btnBorrarCuenta = new javax.swing.JButton();
        btnEliminarFila = new javax.swing.JButton();
        lblMostrarDescuento = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        btnGuardarFactura = new javax.swing.JButton();
        panelVariblesVenta = new javax.swing.JPanel();
        lblTituloFactura = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        cmbVendedores = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnEditarCliente = new javax.swing.JButton();
        btnActualizarClientes = new javax.swing.JButton();
        rbtnBarra = new javax.swing.JRadioButton();
        rbtnMesas = new javax.swing.JRadioButton();
        spnMesas = new javax.swing.JSpinner();
        lblBarraMesa = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        diagCantidades.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        diagCantidades.setAlwaysOnTop(true);
        diagCantidades.setMinimumSize(new java.awt.Dimension(250, 200));
        diagCantidades.setModalityType(null);

        lblTituloCantidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTituloCantidades.setText("Introduce la cantidad");

        spnCantidades.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 1.0f));

        btnCantidadesAceptar.setText("Aceptar");

        javax.swing.GroupLayout diagCantidadesLayout = new javax.swing.GroupLayout(diagCantidades.getContentPane());
        diagCantidades.getContentPane().setLayout(diagCantidadesLayout);
        diagCantidadesLayout.setHorizontalGroup(
            diagCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diagCantidadesLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(diagCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloCantidades, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(spnCantidades))
                .addGap(24, 24, 24))
            .addGroup(diagCantidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCantidadesAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diagCantidadesLayout.setVerticalGroup(
            diagCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagCantidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCantidades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnCantidades, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCantidadesAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(203, 212, 184));

        panelBtnFamilia.setBackground(new java.awt.Color(204, 255, 255));
        panelBtnFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnFamilia.setLayout(new java.awt.GridLayout(3, 0, 1, 1));

        lblFamilias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFamilias.setText("FAMILIAS");

        lblProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductos.setText("PRODUCTOS");

        panelBtnProductos.setBackground(new java.awt.Color(204, 255, 255));
        panelBtnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnProductos.setLayout(new java.awt.GridLayout(9, 0, 1, 1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        panelCuenta.setBackground(new java.awt.Color(204, 255, 255));
        panelCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaCuenta.setBackground(new java.awt.Color(204, 255, 255));
        tablaCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Unidades", "Precio", "Total"
            }
        ));
        tablaCuenta.setGridColor(new java.awt.Color(0, 0, 0));
        scpTablaCuenta.setViewportView(tablaCuenta);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total: ");

        lblPrecioTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecioTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblPrecioTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioTotal.setText("0.0");
        lblPrecioTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBorrarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete.png"))); // NOI18N
        btnBorrarCuenta.setToolTipText("ELIMINAR CUENTA");
        btnBorrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuentaActionPerformed(evt);
            }
        });

        btnEliminarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/erase.png"))); // NOI18N
        btnEliminarFila.setToolTipText("ELIMINAR PRODUCTO");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        lblMostrarDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMostrarDescuento.setForeground(new java.awt.Color(0, 0, 255));
        lblMostrarDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarDescuento.setText("0");
        lblMostrarDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescuento.setText("Dto. %:");

        btnGuardarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Save.png"))); // NOI18N
        btnGuardarFactura.setToolTipText("GUARDAR FACTURA");
        btnGuardarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTablaCuenta)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBorrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                        .addComponent(lblDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                        .addComponent(lblMostrarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addComponent(scpTablaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEliminarFila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescuento))
                            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMostrarDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                        .addComponent(btnBorrarCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnGuardarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelVariblesVenta.setBackground(new java.awt.Color(204, 255, 255));
        panelVariblesVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloFactura.setText("Nº Factura:");

        lblFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblFactura.setOpaque(true);

        lblVendedor.setText("Vendedor:");

        lblCliente.setText("Cliente:");

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setText("Editar clientes");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnActualizarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh.png"))); // NOI18N
        btnActualizarClientes.setToolTipText("ACTUALIZAR LISTA DE CLIENTES");
        btnActualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClientesActionPerformed(evt);
            }
        });

        rbtnBarra.setBackground(new java.awt.Color(204, 255, 255));
        btnGrpBarraMesas.add(rbtnBarra);
        rbtnBarra.setSelected(true);
        rbtnBarra.setText("BARRA");

        rbtnMesas.setBackground(new java.awt.Color(204, 255, 255));
        btnGrpBarraMesas.add(rbtnMesas);
        rbtnMesas.setText("MESA:");

        spnMesas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnMesas.setEnabled(false);

        lblBarraMesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBarraMesa.setForeground(new java.awt.Color(0, 0, 255));
        lblBarraMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarraMesa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHora.setOpaque(true);

        javax.swing.GroupLayout panelVariblesVentaLayout = new javax.swing.GroupLayout(panelVariblesVenta);
        panelVariblesVenta.setLayout(panelVariblesVentaLayout);
        panelVariblesVentaLayout.setHorizontalGroup(
            panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVariblesVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloFactura)
                .addGap(18, 18, 18)
                .addComponent(lblFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbVendedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblCliente)
                .addGap(23, 23, 23)
                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnBarra)
                    .addGroup(panelVariblesVentaLayout.createSequentialGroup()
                        .addComponent(rbtnMesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBarraMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelVariblesVentaLayout.setVerticalGroup(
            panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVariblesVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblBarraMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelVariblesVentaLayout.createSequentialGroup()
                            .addComponent(rbtnBarra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtnMesas)
                                .addComponent(spnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTituloFactura))
                    .addGroup(panelVariblesVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVendedor)
                        .addComponent(cmbVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCliente)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logoGorro.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFamilias)
                            .addComponent(panelBtnFamilia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductos)))
                    .addComponent(panelVariblesVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVariblesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBtnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFamilias))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBtnFamilia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        frame.getBarraMenus().setVisible(true);
        frame.setSize(800, 800);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBorrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuentaActionPerformed
        acciones.vaciarCuenta();
    }//GEN-LAST:event_btnBorrarCuentaActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        acciones.eliminarFila();
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        FrameClientes frame = new FrameClientes();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        acciones.cargarDescuento();
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void btnActualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClientesActionPerformed
        acciones.cargarClientes();
    }//GEN-LAST:event_btnActualizarClientesActionPerformed

    private void btnGuardarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFacturaActionPerformed
        acciones.guardarFactura();
    }//GEN-LAST:event_btnGuardarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarClientes;
    private javax.swing.JButton btnBorrarCuenta;
    private javax.swing.JButton btnCantidadesAceptar;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.ButtonGroup btnGrpBarraMesas;
    private javax.swing.JButton btnGuardarFactura;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbVendedores;
    private javax.swing.JDialog diagCantidades;
    private javax.swing.JLabel lblBarraMesa;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFamilias;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMostrarDescuento;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTituloCantidades;
    private javax.swing.JLabel lblTituloFactura;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel panelBtnFamilia;
    private javax.swing.JPanel panelBtnProductos;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelVariblesVenta;
    private javax.swing.JRadioButton rbtnBarra;
    private javax.swing.JRadioButton rbtnMesas;
    private javax.swing.JScrollPane scpTablaCuenta;
    private javax.swing.JSpinner spnCantidades;
    private javax.swing.JSpinner spnMesas;
    private javax.swing.JTable tablaCuenta;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter del panelBtnFamilia
     *
     * @return JPanel panelBtnFamilia
     */
    public JPanel getPanelBtnFamilia() {
        return panelBtnFamilia;
    }

    /**
     * Getter del panelBtnProductos
     *
     * @return JPanel panelBtnProductos
     */
    public JPanel getPanelBtnProductos() {
        return panelBtnProductos;
    }

    /**
     * Getter del scpTablaCuenta
     *
     * @return JScrollPane scpTablaCuenta
     */
    public JScrollPane getScpTablaCuenta() {
        return scpTablaCuenta;
    }

    /**
     * Getter de la tablaCuenta
     *
     * @return JTable tablaCuenta
     */
    public JTable getTablaCuenta() {
        return tablaCuenta;
    }

    /**
     * Getter del lblPrecioTotal
     *
     * @return JLabel precioTotal
     */
    public JLabel getLblPrecioTotal() {
        return lblPrecioTotal;
    }

    /**
     * Getter del diagCantidades
     *
     * @return JDialogCantidades
     */
    public JDialog getDiagCantidades() {
        return diagCantidades;
    }

    /**
     * Getter deñ spnCantidades
     *
     * @return JSpinner spnCantidades
     */
    public JSpinner getSpnCantidades() {
        return spnCantidades;
    }

    /**
     * Getter del btnCantidadesAceptar(diagCantidades)
     *
     * @return JButton cantidadesAceptar
     */
    public JButton getBtnCantidadesAceptar() {
        return btnCantidadesAceptar;
    }

    /**
     * Getter del btnEliminarFila
     *
     * @return JButton eliminarFila
     */
    public JButton getBtnEliminarFila() {
        return btnEliminarFila;
    }

    /**
     * Getter del cmbVendedores
     *
     * @return JComboBox vendedores
     */
    public JComboBox getCmbVendedores() {
        return cmbVendedores;
    }

    /**
     * Getter del cmbCliente
     *
     * @return JComboBox cliente
     */
    public JComboBox getCmbCliente() {
        return cmbCliente;
    }

    /**
     * Getter del lblMostrarDescuento
     *
     * @return JLabel mostrarDescuento
     */
    public JLabel getLblMostrarDescuento() {
        return lblMostrarDescuento;
    }

    /**
     * Getter del lblBarraMesas
     *
     * @return JLabel barraMesas
     */
    public JLabel getLblBarraMesa() {
        return lblBarraMesa;
    }

    /**
     * Getter del rBtnBarra
     *
     * @return JRadioButton barra
     */
    public JRadioButton getRbtnBarra() {
        return rbtnBarra;
    }

    /**
     * Getter del rBtnMesas
     *
     * @return JRadioButton mesas
     */
    public JRadioButton getRbtnMesas() {
        return rbtnMesas;
    }

    /**
     * Getter del spnMesas
     *
     * @return JSpinner mesas
     */
    public JSpinner getSpnMesas() {
        return spnMesas;
    }

    /**
     * Getter del lblFactura
     *
     * @return JLabel factura
     */
    public JLabel getLblFactura() {
        return lblFactura;
    }

}
