/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Empleados.entities.AccionesEmpleado;
import Principal.TPVFrame;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author yosua
 */
public class PanelEmpleados extends javax.swing.JPanel {

    private TPVFrame frame;
    private AccionesEmpleado acciones;

    public PanelEmpleados(TPVFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesEmpleado(this);
        acciones.cargarLoging();
        acciones.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoging = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        passPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        frameAddEmpleado = new javax.swing.JFrame();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblPassConfirm = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        passPass = new javax.swing.JPasswordField();
        passPassConfirm = new javax.swing.JPasswordField();
        btnAceptarNuevo = new javax.swing.JButton();
        btnCancelarNuevo = new javax.swing.JButton();
        frameEditarEmpleado = new javax.swing.JFrame();
        lblNombreEditar = new javax.swing.JLabel();
        lblApellido1Editar = new javax.swing.JLabel();
        lblApellido2Editar = new javax.swing.JLabel();
        lblPassEditarVieja = new javax.swing.JLabel();
        lblPassEditar = new javax.swing.JLabel();
        lblPassEditarConfirm = new javax.swing.JLabel();
        txtNombreEditar = new javax.swing.JTextField();
        txtApellido1Editar = new javax.swing.JTextField();
        txtApellido2Editar = new javax.swing.JTextField();
        passPassEditarAntigua = new javax.swing.JPasswordField();
        passPassEditar = new javax.swing.JPasswordField();
        passPassEditarConfrim = new javax.swing.JPasswordField();
        btnAceptarEditar = new javax.swing.JButton();
        btnCancelarEditar = new javax.swing.JButton();
        scpTablaEmpleados = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnAniadir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        panelLoging.setMinimumSize(new java.awt.Dimension(800, 800));
        panelLoging.setPreferredSize(new java.awt.Dimension(800, 800));

        lblUsuario.setText("Usuario:");

        passPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPasswordActionPerformed(evt);
            }
        });

        lblPassword.setText("Contraseña:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogingLayout = new javax.swing.GroupLayout(panelLoging);
        panelLoging.setLayout(panelLogingLayout);
        panelLogingLayout.setHorizontalGroup(
            panelLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblUsuario))
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lblPassword))
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(passPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnAceptar))
        );
        panelLogingLayout.setVerticalGroup(
            panelLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogingLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(lblUsuario)
                .addGap(21, 21, 21)
                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(passPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar))
        );

        frameAddEmpleado.setTitle("Añadir empleado");
        frameAddEmpleado.setMinimumSize(new java.awt.Dimension(500, 400));

        lblNombre.setText("Nombre:");

        lblApellido1.setText("Apellido 1:");

        lblApellido2.setText("Apellido 2:");

        lblPass.setText("Contraseña:");

        lblPassConfirm.setText("Contraseña:");

        btnAceptarNuevo.setText("Aceptar");
        btnAceptarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNuevoActionPerformed(evt);
            }
        });

        btnCancelarNuevo.setText("Cancelar");
        btnCancelarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameAddEmpleadoLayout = new javax.swing.GroupLayout(frameAddEmpleado.getContentPane());
        frameAddEmpleado.getContentPane().setLayout(frameAddEmpleadoLayout);
        frameAddEmpleadoLayout.setHorizontalGroup(
            frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAddEmpleadoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido1)
                    .addComponent(lblApellido2)
                    .addComponent(lblPass)
                    .addComponent(lblPassConfirm))
                .addGap(27, 27, 27)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAddEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnAceptarNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarNuevo))
                    .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(txtApellido1)
                        .addComponent(txtApellido2)
                        .addComponent(passPass)
                        .addComponent(passPassConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        frameAddEmpleadoLayout.setVerticalGroup(
            frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAddEmpleadoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido2)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(passPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassConfirm)
                    .addComponent(passPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameAddEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarNuevo)
                    .addComponent(btnCancelarNuevo))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        frameEditarEmpleado.setTitle("Editar empleado");
        frameEditarEmpleado.setMinimumSize(new java.awt.Dimension(600, 500));

        lblNombreEditar.setText("Nombre:");

        lblApellido1Editar.setText("Apellido 1:");

        lblApellido2Editar.setText("Apellido 2:");

        lblPassEditarVieja.setText("Antigua Contraseña: ");

        lblPassEditar.setText("Contraseña nueva:");

        lblPassEditarConfirm.setText("Contraseña nueva:");

        btnAceptarEditar.setText("Aceptar");
        btnAceptarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditarActionPerformed(evt);
            }
        });

        btnCancelarEditar.setText("Cancelar");
        btnCancelarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameEditarEmpleadoLayout = new javax.swing.GroupLayout(frameEditarEmpleado.getContentPane());
        frameEditarEmpleado.getContentPane().setLayout(frameEditarEmpleadoLayout);
        frameEditarEmpleadoLayout.setHorizontalGroup(
            frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarEmpleadoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEditar)
                    .addComponent(lblApellido1Editar)
                    .addComponent(lblApellido2Editar)
                    .addComponent(lblPassEditarVieja)
                    .addComponent(lblPassEditar)
                    .addComponent(lblPassEditarConfirm))
                .addGap(27, 27, 27)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameEditarEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnAceptarEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEditar))
                    .addComponent(txtNombreEditar)
                    .addComponent(txtApellido1Editar)
                    .addComponent(txtApellido2Editar)
                    .addComponent(passPassEditarAntigua)
                    .addComponent(passPassEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(passPassEditarConfrim))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        frameEditarEmpleadoLayout.setVerticalGroup(
            frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarEmpleadoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEditar)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1Editar)
                    .addComponent(txtApellido1Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido2Editar)
                    .addComponent(txtApellido2Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassEditarVieja)
                    .addComponent(passPassEditarAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassEditar)
                    .addComponent(passPassEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassEditarConfirm)
                    .addComponent(passPassEditarConfrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(frameEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarEditar)
                    .addComponent(btnCancelarEditar))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(800, 800));

        tablaEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido 1", "Apellido 2"
            }
        ));
        scpTablaEmpleados.setViewportView(tablaEmpleados);

        panelBotones.setLayout(new java.awt.GridLayout(1, 0));

        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add.png"))); // NOI18N
        btnAniadir.setToolTipText("Añadir empleado");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });
        panelBotones.add(btnAniadir);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar empleado");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        btnBorrar.setToolTipText("Eliminar empleado");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnBorrar);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelBotones.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scpTablaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        acciones.usuarioValido();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        frameAddEmpleado.setLocationRelativeTo(this);
        frameAddEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnCancelarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNuevoActionPerformed
        frameAddEmpleado.dispose();
    }//GEN-LAST:event_btnCancelarNuevoActionPerformed

    private void btnAceptarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNuevoActionPerformed
        acciones.guardarEmpleado();
    }//GEN-LAST:event_btnAceptarNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        acciones.eliminarEmpleado();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void passPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPasswordActionPerformed
        acciones.usuarioValido();
    }//GEN-LAST:event_passPasswordActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        acciones.editarEmpleado();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarActionPerformed
        frameEditarEmpleado.dispose();
    }//GEN-LAST:event_btnCancelarEditarActionPerformed

    private void btnAceptarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditarActionPerformed
        acciones.guardarModificacion();
    }//GEN-LAST:event_btnAceptarEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarEditar;
    private javax.swing.JButton btnAceptarNuevo;
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelarEditar;
    private javax.swing.JButton btnCancelarNuevo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JFrame frameAddEmpleado;
    private javax.swing.JFrame frameEditarEmpleado;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido1Editar;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblApellido2Editar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEditar;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassConfirm;
    private javax.swing.JLabel lblPassEditar;
    private javax.swing.JLabel lblPassEditarConfirm;
    private javax.swing.JLabel lblPassEditarVieja;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelLoging;
    private javax.swing.JPasswordField passPass;
    private javax.swing.JPasswordField passPassConfirm;
    private javax.swing.JPasswordField passPassEditar;
    private javax.swing.JPasswordField passPassEditarAntigua;
    private javax.swing.JPasswordField passPassEditarConfrim;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JScrollPane scpTablaEmpleados;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido1Editar;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtApellido2Editar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEditar;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter del panelLoging
     *
     * @return Jpanel panelLoging
     */
    public JPanel getPanelLoging() {
        return panelLoging;
    }

    /**
     * Getter del cmbUsuarios(panelLoging)
     *
     * @return ComboBox cmbUsuarios
     */
    public JComboBox getCmbUsuarios() {
        return cmbUsuarios;
    }

    /**
     * Getter del passPassword(panelLoging)
     *
     * @return JPasswordField passPassword
     */
    public JPasswordField getPassPassword() {
        return passPassword;
    }

    /**
     * Getter del frame
     *
     * @return TPVFrame frame
     */
    public TPVFrame getFrame() {
        return frame;
    }

    /**
     * Getter del scpTablaEmpleados
     *
     * @return JScrollPane scpTablaEmpleados
     */
    public JScrollPane getScpTablaEmpleados() {
        return scpTablaEmpleados;
    }

    /**
     * Getter de tablaEmpleados
     *
     * @return JTable tablaEmpleados
     */
    public JTable getTablaEmpleados() {
        return tablaEmpleados;
    }

    /**
     * Getter del passPass(frameAddEmpleado)
     *
     * @return JPasswordField passPass
     */
    public JPasswordField getPassPass() {
        return passPass;
    }

    /**
     * Getter del passPassConfirm(frameAddEmpleado)
     *
     * @return JPasswordField passPassConfirm
     */
    public JPasswordField getPassPassConfirm() {
        return passPassConfirm;
    }

    /**
     * Getter del txtApellido1(frameAddEmpleado)
     *
     * @return JTextField txtApellido1
     */
    public JTextField getTxtApellido1() {
        return txtApellido1;
    }

    /**
     * Getter del txtApellido2(frameAddEmpleado)
     *
     * @return JTextField txtApellido2
     */
    public JTextField getTxtApellido2() {
        return txtApellido2;
    }

    /**
     * Getter del txtnombre(frameAddEmpleado)
     *
     * @return JTextField txtNombre
     */
    public JTextField getTxtNombre() {
        return txtNombre;
    }

    /**
     * Getter del frameAddEmpleado
     *
     * @return JFrame frameAddEmpleado
     */
    public JFrame getFrameAddEmpleado() {
        return frameAddEmpleado;
    }

    /**
     * Getter del passPassEditar(frameEditarEmpleado)
     *
     * @return JPasswordField passPassEditar
     */
    public JPasswordField getPassPassEditar() {
        return passPassEditar;
    }

    /**
     * Getter del passPassEditarAntigua(frameEditarEmpleado)
     *
     * @return JPasswordField passPassEditarAntigua
     */
    public JPasswordField getPassPassEditarAntigua() {
        return passPassEditarAntigua;
    }

    /**
     * Getter del passPassEditarConfirm(frameEditarEmpleado)
     *
     * @return JPasswordField passPassEditarConfirm
     */
    public JPasswordField getPassPassEditarConfrim() {
        return passPassEditarConfrim;
    }

    /**
     * Getter del txtApellido1Editar(frameEditarEmpleado)
     *
     * @return JTextField txtApellido1Editar
     */
    public JTextField getTxtApellido1Editar() {
        return txtApellido1Editar;
    }

    /**
     * Getter del txtAepllido2Editar(frameEditarEmpleado)
     *
     * @return JTextField txtApellido2Editar
     */
    public JTextField getTxtApellido2Editar() {
        return txtApellido2Editar;
    }

    /**
     * Getter del txtNombreEditar(frameEditarEmpleado)
     *
     * @return JTextField txtNombreEditar
     */
    public JTextField getTxtNombreEditar() {
        return txtNombreEditar;
    }

    /**
     * Getter del frameEditarEmpleado
     *
     * @return JFrame frameEditarEmpleado
     */
    public JFrame getFrameEditarEmpleado() {
        return frameEditarEmpleado;
    }

}
