/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Familias.entities.AccionesFamilia;
import Principal.TPVFrame;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author yosua
 */
public class PanelFamilias extends javax.swing.JPanel {

    private TPVFrame frame;
    private AccionesFamilia acciones;

    public PanelFamilias(TPVFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesFamilia(this);
        acciones.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameAddFamilia = new javax.swing.JFrame();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblIcono = new javax.swing.JLabel();
        txtRutaIcono = new javax.swing.JTextField();
        btnRuta = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMostrar = new javax.swing.JLabel();
        frameEditarFamilia = new javax.swing.JFrame();
        lblNombreEditar = new javax.swing.JLabel();
        txtNombreEditar = new javax.swing.JTextField();
        lblIconoEditar = new javax.swing.JLabel();
        txtRutaIconoEditar = new javax.swing.JTextField();
        btnRutaEditar = new javax.swing.JButton();
        btnAceptarEditar = new javax.swing.JButton();
        btnCancelarEditar = new javax.swing.JButton();
        lblMostrarEditar = new javax.swing.JLabel();
        scpTablaFamilias = new javax.swing.JScrollPane();
        tablaFamilias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        frameAddFamilia.setTitle("Editar familia");
        frameAddFamilia.setMinimumSize(new java.awt.Dimension(450, 300));

        lblNombre.setText("Nombre de la familia:");

        lblIcono.setText("Ruta del icono:");

        btnRuta.setText("Buscar");
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblMostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMostrar.setMaximumSize(new java.awt.Dimension(8, 8));
        lblMostrar.setMinimumSize(new java.awt.Dimension(8, 8));
        lblMostrar.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout frameAddFamiliaLayout = new javax.swing.GroupLayout(frameAddFamilia.getContentPane());
        frameAddFamilia.getContentPane().setLayout(frameAddFamiliaLayout);
        frameAddFamiliaLayout.setHorizontalGroup(
            frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAddFamiliaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameAddFamiliaLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblIcono)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre)
                        .addComponent(txtRutaIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRuta)
                    .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        frameAddFamiliaLayout.setVerticalGroup(
            frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAddFamiliaLayout.createSequentialGroup()
                .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAddFamiliaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIcono)
                        .addGap(18, 18, 18)
                        .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRutaIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRuta))
                        .addGap(18, 18, 18)
                        .addGroup(frameAddFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar)))
                    .addGroup(frameAddFamiliaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        frameEditarFamilia.setTitle("Añadir familia");
        frameEditarFamilia.setMinimumSize(new java.awt.Dimension(450, 300));

        lblNombreEditar.setText("Nombre de la familia:");

        lblIconoEditar.setText("Ruta del icono:");

        btnRutaEditar.setText("Buscar");
        btnRutaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaEditarActionPerformed(evt);
            }
        });

        btnAceptarEditar.setText("Aceptar");
        btnAceptarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditarActionPerformed(evt);
            }
        });

        btnCancelarEditar.setText("Cancelar");
        btnCancelarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarActionPerformed(evt);
            }
        });

        lblMostrarEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMostrarEditar.setMaximumSize(new java.awt.Dimension(8, 8));
        lblMostrarEditar.setMinimumSize(new java.awt.Dimension(8, 8));
        lblMostrarEditar.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout frameEditarFamiliaLayout = new javax.swing.GroupLayout(frameEditarFamilia.getContentPane());
        frameEditarFamilia.getContentPane().setLayout(frameEditarFamiliaLayout);
        frameEditarFamiliaLayout.setHorizontalGroup(
            frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarFamiliaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEditarFamiliaLayout.createSequentialGroup()
                        .addComponent(btnAceptarEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEditar))
                    .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblIconoEditar)
                        .addComponent(lblNombreEditar)
                        .addComponent(txtNombreEditar)
                        .addComponent(txtRutaIconoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRutaEditar)
                    .addComponent(lblMostrarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        frameEditarFamiliaLayout.setVerticalGroup(
            frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarFamiliaLayout.createSequentialGroup()
                .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameEditarFamiliaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblNombreEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIconoEditar)
                        .addGap(18, 18, 18)
                        .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRutaIconoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRutaEditar))
                        .addGap(18, 18, 18)
                        .addGroup(frameEditarFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarEditar)
                            .addComponent(btnCancelarEditar)))
                    .addGroup(frameEditarFamiliaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblMostrarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tablaFamilias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Familia"
            }
        ));
        scpTablaFamilias.setViewportView(tablaFamilias);

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add.png"))); // NOI18N
        btnAdd.setToolTipText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        btnBorrar.setToolTipText("Eliminar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scpTablaFamilias, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTablaFamilias, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frameAddFamilia.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        acciones.buscarIcono();
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtNombre.setText("");
        txtRutaIcono.setText("");
        lblMostrar.setIcon(null);
        frameAddFamilia.setLocationRelativeTo(this);
        frameAddFamilia.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        acciones.guardarFamilia();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        acciones.eliminarFamilia();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRutaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaEditarActionPerformed
        acciones.buscarIcono();
    }//GEN-LAST:event_btnRutaEditarActionPerformed

    private void btnAceptarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditarActionPerformed
        acciones.guardarModificacion();
    }//GEN-LAST:event_btnAceptarEditarActionPerformed

    private void btnCancelarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarActionPerformed
        frameEditarFamilia.dispose();
    }//GEN-LAST:event_btnCancelarEditarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        acciones.editarFamilia();
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarEditar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarEditar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRuta;
    private javax.swing.JButton btnRutaEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFrame frameAddFamilia;
    private javax.swing.JFrame frameEditarFamilia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIconoEditar;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblMostrarEditar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEditar;
    private javax.swing.JScrollPane scpTablaFamilias;
    private javax.swing.JTable tablaFamilias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEditar;
    private javax.swing.JTextField txtRutaIcono;
    private javax.swing.JTextField txtRutaIconoEditar;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter del scpTablaFamilias
     *
     * @return JScrollPane scpTablaFamilias
     */
    public JScrollPane getScpTablaFamilias() {
        return scpTablaFamilias;
    }

    /**
     * Getter de tablaFamilias
     *
     * @return JTable tablaFamilias
     */
    public JTable getTablaFamilias() {
        return tablaFamilias;
    }

    /**
     * Getter del txtNombre
     *
     * @return JTextField txtNombre
     */
    public JTextField getTxtNombre() {
        return txtNombre;
    }

    /**
     * Getter del txtRutaIcono
     *
     * @return JTextField txtRutaIcono
     */
    public JTextField getTxtRutaIcono() {
        return txtRutaIcono;
    }

    /**
     * Getter del lblMostrar
     *
     * @return JLabel lblMostrar
     */
    public JLabel getLblMostrar() {
        return lblMostrar;
    }

    /**
     * Getter del frameAddFamilia
     *
     * @return JFrame frameAddFamilia
     */
    public JFrame getFrameAddFamilia() {
        return frameAddFamilia;
    }

    /**
     * Getter del lblMostrarEditar(frameEditarFamilia)
     *
     * @return JLabel lblMostrarEditar
     */
    public JLabel getLblMostrarEditar() {
        return lblMostrarEditar;
    }

    /**
     * Getter del txtNombreEditar(frameEditarFamilia)
     *
     * @return JTextField txtNombreEditar
     */
    public JTextField getTxtNombreEditar() {
        return txtNombreEditar;
    }

    /**
     * Getter del txtRutaIconoEditar(frameEditarFamilia)
     *
     * @return JTextField txtRutaIconoEditar
     */
    public JTextField getTxtRutaIconoEditar() {
        return txtRutaIconoEditar;
    }

    /**
     * Getter del frameEditarFamilia
     *
     * @return JFrame frameEditarFamilia
     */
    public JFrame getFrameEditarFamilia() {
        return frameEditarFamilia;
    }

}
